### ISSUE TITLE
AMD W9100 not supported

### ISSUE THREAD

**Issue by MUSTDOS** [Djdefrag/FluidFrames.RIFE#3]
How do I know which GPUs are properly supported?

**Comment by Djdefrag** [comment]
Hi my friend,

you can use GPUZ (https://www.techpowerup.com/gpuz/)

and check if DirectML is checked

![2023_12_01_14_44_04_guru3d_RealESR_Gx4_Resize-100_Interpolation-High](https://github.com/user-attachments/assets/b34be2ba-ad8e-47f7-8cc9-3b9207369cbd)

**Comment by MUSTDOS** [comment]
![image](https://github.com/user-attachments/assets/9d4d3181-ffef-4ffd-9dab-13071b1f0909)
Yup

**Comment by Djdefrag** [comment]
So your GPU is compatible :)

**Comment by MUSTDOS** [comment]
Oddly, it's my CPU that takes all the load if I set the gpu to 1 which is the first one.

**Comment by MUSTDOS** [comment]
![image](https://github.com/user-attachments/assets/1f2d3bed-7f81-46ad-98b3-55b998f6ae97)

**Comment by Djdefrag** [comment]
Mh probably you are missing some libraries.

PREREQUISITES.
1. (If not already installed) install Visual-C-Runtimes: 
   - https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

2. (If not already installed) install Directx:
   - https://www.microsoft.com/it-it/download/details.aspx?id=35

Install this and reboot the PC

**Comment by Djdefrag** [comment]
AH sorry, but i see an error message in the console ...Available providers "AzureExecutionProvider"...

are you on a Windows Virtual machine?

**Comment by Djdefrag** [comment]
Also, i see on AMD website that the official drivers for r9 290x are

![image](https://github.com/user-attachments/assets/8e05f33a-1c39-4cc0-a27f-bd0f7a5bea29)

that are different from yours

**Comment by MUSTDOS** [comment]
I had to get my drivers from here since AMD stopped releasing updates and was becoming more incompatible each day https://sourceforge.net/projects/radeon-id-distribution/ It's W9100 but it sees it as the r9 290x for having the same architecture

**Comment by MUSTDOS** [comment]
Silly me!!!

I'm new to python and forgot to install all onnxruntime extensions from pip!

**Comment by Djdefrag** [comment]
Ah perfect my friend! 

I will add more info about this
